version: '3'

services:
  mkdocs:
    container_name: mkdocs
    command: serve --dev-addr=0.0.0.0:8000 --no-livereload
    image: squidfunk/mkdocs-material
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - "${PWD}:/docs"
